#服务配置
server:
  #端口
  port: 7071
  #服务编码
  tomcat:
    uri-encoding: UTF-8
#spring相关配置
spring:
  main:
    allow-bean-definition-overriding: true
  redis:
    redisson:
      config: classpath:singleServerConfig.yaml
    host: 192.168.112.77
    port: 6379
    password: pass
  cloud:
    alicloud:
      access-key: LTAI4G2g6WqYBZyZMovev1pd
      secret-key: 2Q4x5TpgHRP8Eo3ehQzCJxPteBl4R4
      oss:
        bucket-name: itheima-sh-oss
        endpoint: oss-cn-shanghai.aliyuncs.com
  #数据源配置
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.112.77:3306/restkeeper-basic?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
      username: root
      password: pass
#mybatis配置
mybatis-plus:
  # MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: com.itheima.springcloud.pojo
  # 该配置请和 typeAliasesPackage 一起使用，如果配置了该属性，则仅仅会扫描路径下以该类作为父类的域对象 。
  type-aliases-super-type: com.itheima.restkeeper.basic.BasicPojo
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 驼峰下划线转换
    map-underscore-to-camel-case: true
    use-generated-keys: true
    default-statement-timeout: 60
    default-fetch-size: 100
  #忽略商户号表
  ignore-enterprise-tables:
    - tab_places
    - tab_affix
    - tab_log_business
    - tab_data_dict
    - tab_sms_blacklist
    - tab_sms_channel
    - tab_sms_send_record
    - tab_sms_sign
    - tab_sms_template
    - undo_log
  #忽略门店号表
  ignore-store-tables:
    - tab_places
    - tab_affix
    - tab_log_business
    - tab_data_dict
    - tab_sms_blacklist
    - tab_sms_channel
    - tab_sms_send_record
    - tab_sms_sign
    - tab_sms_template
    - undo_log
dubbo:
  application:
    version: 1.0.0
    logger: slf4j
  scan:
    base-packages: com.itheima.restkeeper
  registry:
    address: spring-cloud://192.168.112.77
  protocol:
    #指定二进制协议
    name: dubbo
    port: 27071
    threads: 200
    accesslog: D:/logs/model-basic-producer-01.log